---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
#words_of_champions <- read.csv(file = "words_of_champions_2022.csv")
```


```{r}
read_word_list <- function(filename) {
  x <- readLines(filename)
  if (length(grep("--", x)) > 0)
    x <- x[-(1:grep("--", x))]
  x <- x[sapply(x, str_length) > 0]
  
  new_word_loc <- grep("***", x, fixed = TRUE)[1]
  if (is.na(new_word_loc)) {
    new_word_loc <- length(x) + 1
  }

  alt_loc <- grep("-OR-", x)
  
  alt_words <- x[alt_loc]

  if (sum(grepl("-OR-", alt_words)) > 0) {
    alt_words_df <-
      str_split(alt_words, "-OR-") %>% 
      unlist() %>%
      matrix(nrow = 2) %>%
      t() %>% 
      data.frame()
    colnames(alt_words_df) <- c("word", "alt")
    
    x <- bind_rows(tibble(word = x[-alt_loc], alt = ""),
                   tibble(alt_words_df))
  } else {
    x <- tibble(word = x, alt = "")
  }

  x <- cbind(x, new_word = 1)
  x$new_word[1:(new_word_loc-1)] <- 0
  
  x
}
```

```{r}
word_list_2022_files <-
  c(
    onebee_study = "2022-word-list-onebee-study.txt",
    onebee_champions = "2022-word-list-onebee-champions.txt",
    twobee_study = "2022-word-list-twobee-study.txt",
    twobee_champions = "2022-word-list-twobee-champions.txt",
    threebee_study = "2022-word-list-threebee-study.txt",
    threebee_champions = "2022-word-list-threebee-champions.txt"
  )
```


```{r}
word_list_2022 <-
  lapply(word_list_2022_files,
         read_word_list) %>%
  bind_rows(.id = "id") %>%
  mutate(bee = sub("bee", "", sub("_.+$", "", id)),
         group = sub("^.+_", "", id)) %>%
  mutate(nTried = 0, nMistakes = 0, weight = 1)

word_list_2022$id <- 1:nrow(word_list_2022)
```


```{r}
words_of_champions <- word_list_2022
```

```{r}
words_of_extreme <- read_csv("merged_word_rev2019-03-24.csv")
```




```{r}
level2bee_names <- c(unique(words_of_extreme$level))

level2bee <- c("two", "two", "one", "three")

names(level2bee) <- level2bee_names

level2bee
```



```{r}
words_of_extreme %>% 
  mutate(bee = level2bee[level]) ->
  words_of_extreme
```

```{r}
words_of_extreme %>% 
  filter(group != "CWL") ->
  words_of_extreme
```


```{r}
words_of_extreme %>%
  mutate(group_org = group) %>%
  mutate(group = "extreme") ->
  words_of_extreme
```

```{r}
words_of_extreme %>% 
  filter(!(word %in% words_of_champions$word)) ->
  words_of_extreme
```

```{r}
words_of_extreme %>% 
  select(word, group, bee) %>%
  full_join(words_of_champions, ., by = c("word", "bee", "group")) %>%
  replace_na(list(new_word = 0, alt = "")) ->
  words_of_extreme
```

```{r}
words_of_extreme$id <- 1:nrow(words_of_extreme)
words_of_extreme$nTried <- 0
words_of_extreme$nMistakes <- 0
words_of_extreme$weight <- 1
```


```{r}
write_csv(words_of_champions, file = "words_of_champions_2022.csv")
write_csv(words_of_extreme, file = "words_of_extreme_2022.csv")
```


```{r}
library(jsonlite)
```

```{r}
write_json(words_of_champions, path = "words_of_champions_2022.json", pretty = TRUE)
write_json(words_of_champions, path = "words_of_champions.json", pretty = TRUE)
```


```{r}
write_json(words_of_extreme, path = "words_of_extreme_2022.json", pretty = TRUE)
write_json(words_of_extreme, path = "words_of_extreme.json", pretty = TRUE)
```

```{r}
old_woc_filename <- "words_of_champions_2021.json"
archived_dir <- "../archived"
read_json(file.path(archived_dir, old_woc_filename)) %>%
  bind_rows() %>%
  mutate(new_word = 0) %>%
  write_json(path = old_woc_filename, pretty = TRUE)
```


```{r}
old_woc_filename <- "words_of_extreme_2021.json"
archived_dir <- "../archived"
read_json(file.path(archived_dir, old_woc_filename)) %>%
  bind_rows() %>%
  mutate(new_word = 0) %>%
  write_json(path = old_woc_filename, pretty = TRUE)
```

